name: .NET CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --no-restore

    - name: Build Docker Image
      run: docker build -t devops-app .

      ## added

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Tag Docker Image
      run: docker tag devops-app ${{ secrets.DOCKER_USERNAME }}/devops-app:latest

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/devops-app:latest

  deploy:
      needs: build
      runs-on: ubuntu-latest

      steps:
        - name: Deploy to EC2
          uses: appleboy/ssh-action@v1.0.0
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USER }}
            key: ${{ secrets.EC2_KEY }}
            script: |
              sudo docker pull madhurichavan612/devops-app:latest
              sudo docker stop devops-container || true
              sudo docker rm devops-container || true
              sudo docker run -d -p 5000:8080 --name devops-container madhurichavan612/devops-app